# Generated by Django 5.0.6 on 2026-07-09 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        ("documents", "0001_initial"),
        ("frameworks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="documents",
            field=models.ManyToManyField(
                blank=True, related_name="assessments", to="documents.uploadeddocument"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="framework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessments",
                to="frameworks.framework",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="assessments.assessment",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="chunk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evidence",
                to="documents.documentchunk",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evidence",
                to="documents.uploadeddocument",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evidence",
                to="frameworks.requirement",
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["status", "-created_at"], name="assessments_status_be3ff1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(
                fields=["assessment", "requirement_identifier"],
                name="assessments_assessm_f599f9_idx",
            ),
        ),
    ]
