# Generated by Django 5.0.6 on 2026-07-09 14:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor_role", models.CharField(blank=True, max_length=32)),
                ("actor_label", models.CharField(blank=True, max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("UPLOAD", "Upload"),
                            ("PROCESS", "Process"),
                            ("REPROCESS", "Reprocess"),
                            ("OVERRIDE", "Human Override"),
                            ("EXPORT", "Export"),
                            ("SYNC", "Framework Sync"),
                            ("LOGIN", "Login"),
                            ("VIEW", "View"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "entity_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
