# Generated by Django 5.0.6 on 2026-07-09 14:12

import documents.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chunk_index", models.PositiveIntegerField()),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "chunk_type",
                    models.CharField(
                        choices=[
                            ("RECURSIVE", "Recursive"),
                            ("PAGE", "Page"),
                            ("TABLE", "Table"),
                        ],
                        default="RECURSIVE",
                        max_length=16,
                    ),
                ),
                ("text", models.TextField()),
                ("char_start", models.PositiveIntegerField(blank=True, null=True)),
                ("char_end", models.PositiveIntegerField(blank=True, null=True)),
                ("token_count", models.PositiveIntegerField(blank=True, null=True)),
                ("embedding_id", models.CharField(blank=True, max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["document_id", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="UploadedDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(upload_to=documents.models.document_upload_path),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("extension", models.CharField(max_length=16)),
                (
                    "mime_type",
                    models.CharField(
                        help_text="Content-sniffed MIME type.", max_length=128
                    ),
                ),
                ("declared_mime_type", models.CharField(blank=True, max_length=128)),
                ("size_bytes", models.BigIntegerField()),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("AI_SYSTEM_DOC", "AI System Documentation"),
                            ("MODEL_CARD", "Model Card"),
                            ("DATASHEET", "Datasheet"),
                            ("SECURITY_POLICY", "Security Policy"),
                            ("GOVERNANCE_POLICY", "Governance Policy"),
                            ("RISK_ASSESSMENT", "Risk Assessment"),
                            ("DPIA", "Data Protection Impact Assessment"),
                            ("SOP", "Standard Operating Procedure"),
                            ("TECHNICAL_PDF", "Technical PDF"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("PROCESSING", "Processing"),
                            ("PROCESSED", "Processed"),
                            ("FAILED", "Failed"),
                        ],
                        default="UPLOADED",
                        max_length=16,
                    ),
                ),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("is_scanned", models.BooleanField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
