# Generated by Django 5.0.6 on 2026-07-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_uploadeddocument_extracted_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentchunk",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
