# Generated by Django 5.0.6 on 2026-07-09 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("REQUIREMENT", "Requirement"),
                            ("CONTROL", "Control"),
                            ("FRAMEWORK", "Framework"),
                            ("OVERALL", "Overall"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "requirement_identifier",
                    models.CharField(blank=True, max_length=128),
                ),
                ("control_id", models.CharField(blank=True, max_length=128)),
                ("label", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PASS", "Pass"),
                            ("PARTIAL", "Partial"),
                            ("FAIL", "Fail"),
                            ("CANNOT_DETERMINE", "Cannot Determine"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("reasoning", models.TextField(blank=True)),
                ("missing_information", models.JSONField(blank=True, default=list)),
                (
                    "weight",
                    models.DecimalField(decimal_places=3, default=0, max_digits=6),
                ),
                (
                    "raw_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "weighted_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "normalized_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("breakdown", models.JSONField(blank=True, default=dict)),
                ("is_human_overridden", models.BooleanField(default=False)),
                ("override_reason", models.TextField(blank=True)),
                ("computed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="assessments.assessment",
                    ),
                ),
            ],
            options={
                "ordering": ["assessment_id", "level", "requirement_identifier"],
            },
        ),
    ]
