# Generated by Django 5.0.6 on 2026-07-09 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("frameworks", "0001_initial"),
        ("scoring", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentscore",
            name="overridden_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="score_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessmentscore",
            name="requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scores",
                to="frameworks.requirement",
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentscore",
            index=models.Index(
                fields=["assessment", "level"], name="scoring_ass_assessm_479181_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentscore",
            index=models.Index(
                fields=["assessment", "status"], name="scoring_ass_assessm_99ce65_idx"
            ),
        ),
    ]
