# Generated by Django 5.0.6 on 2026-07-09 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Framework",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.SlugField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(blank=True, max_length=64)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("category", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("is_active", models.BooleanField(default=True)),
                ("config_hash", models.CharField(blank=True, max_length=64)),
                ("scoring_config", models.JSONField(blank=True, default=dict)),
                ("raw_config", models.JSONField(blank=True, default=dict)),
                ("requirement_count", models.PositiveIntegerField(default=0)),
                ("control_count", models.PositiveIntegerField(default=0)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(
                        help_text="Stable, unique id within the framework, e.g. ISO42001-A.6.2.2",
                        max_length=128,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "control",
                    models.TextField(
                        help_text="The concrete control/measure that satisfies it."
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Relative importance 1-5."
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=255)),
                ("risk_domain", models.CharField(blank=True, max_length=255)),
                ("control_group", models.CharField(blank=True, max_length=128)),
                ("control_group_title", models.CharField(blank=True, max_length=500)),
                ("evidence_expectations", models.JSONField(blank=True, default=list)),
                ("pass_criteria", models.TextField(blank=True)),
                ("partial_criteria", models.TextField(blank=True)),
                ("fail_criteria", models.TextField(blank=True)),
                ("references", models.JSONField(blank=True, default=list)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="frameworks.framework",
                    ),
                ),
            ],
            options={
                "ordering": ["framework_id", "order"],
                "indexes": [
                    models.Index(
                        fields=["framework", "category"],
                        name="frameworks__framewo_e31e5b_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="requirement",
            constraint=models.UniqueConstraint(
                fields=("framework", "identifier"), name="uniq_framework_requirement"
            ),
        ),
    ]
